### ISSUE TITLE
curl returns "Move permanently" instead of random commit message

### ISSUE THREAD

**Issue by mattes3** [omrilotan/espanso-package-wtc#3]
When I use this, I get an HTML page saying that wtc has moved permanently.

Insert "https://" before the URL in the yaml file, and it's done!

**Comment by mrhahn3000** [comment]
The commit with this solution was made 8 days before already...[PR](https://github.com/omrilotan/espanso-package-wtc/pull/2) not sure, why the version is not available yet in the `espanso hub`

**Comment by omrilotan** [comment]
Still waiting for the pull request in the hub:
https://github.com/espanso/hub/pull/54

**Comment by omrilotan** [comment]
Merged: https://github.com/espanso/hub/pull/54#event-7949064849
